format = """
$jobs\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[jobs]
format = "[$symbol]($style) "
style = "red"
symbol = "✦"

[username]
format = "[$user@]($style)"
style_user = "bright-black"

[hostname]
format = "[$hostname]($style) "
style = "bright-black"

[directory]
format = "[$path]($style) "
style = "blue"
truncation_length = 0
truncate_to_repo = false

[git_state]
format = "[$state]($style) "
style = "bright-black"
rebase="rebase"
merge="merge"
revert="revert"
cherry_pick="cherry-pick"
bisect="bisect"
am=""
am_or_rebase=""

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted )](red)($ahead_behind )($stashed )]($style)"
style = "cyan"
conflicted = "​" # zero-width space
untracked = "​" # zero-width space
modified = "​" # zero-width space
staged = "​" # zero-width space
renamed = "​" # zero-width space
deleted = "​" # zero-width space
ahead = "⇡"
behind = "⇣"
diverged = "⇡⇣"
stashed = "≡"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[character]
success_symbol = "[❯](green)" # insert
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](blue)" # normal
vimcmd_replace_one_symbol = "[❮](blue)" # normal
vimcmd_replace_symbol = "[❮](blue)" # normal
vimcmd_visual_symbol = "[❮](purple)" # visual
